### ISSUE TITLE
Excerpts?

### ISSUE THREAD

**Issue by YoungElPaso** [sethen/markdown-include#1]
Great module.  I dunno if this is the venue for this, but I haven't found another module that can do excerpts.  For the purposes of this issue, I'm defining an excerpt as an include+delimiter.  Seems fairly straightforward.  

Any interest in that type of feature?  I'd be happy to contribute if so.

**Comment by sethen** [comment]
Hey there, thanks for the kind words on markdown-include.

Interesting thoughts.  So, what are you thinking?  It's a way to let you define the way the markdown-include parses things?  For instance, something like:

```
include "markdown.md" !myDelimiter
```

In the example above, `myDelimiter` would be something that would be defined by the developer.

Is this kind of what you're thinking??  Just trying to fully understand the request.

Thanks!

**Comment by YoungElPaso** [comment]
Yeah, that's exactly what I was thinking.  I have an example wherein I'm writing a lot (lots and lots) of .md docs and I'd love to be able to have 'index' style pages that would amalgamate a series of excerpts, and refer to the source document for more info.  I figure an excerpt/include feature would be handy for such use cases.

**Comment by sethen** [comment]
Ah.  I will be figuring out what methods markdown-include will expose via a public API in the coming days.  I will update this issue once I make those decisions.  This way anyone can take advantage of the API and decide how to best use markdown-include as they see fit.  I believe the methods are already in place to support something like this though.

**Comment by sethen** [comment]
This functionality has made it's way into markdown-include and is on the 0.3.2 branch which will be merged into master soon.

When using markdown-include as a module, you can define custom tags by adding to the `customTags` object on the markdown-include module.  The will be looked at anytime the object has proper keys in it.

I will be updating the documentation in 0.3.2 to go into more detail about how this actually works.

Thanks for the request!

**Comment by sethen** [comment]
Merged into master.
