### ISSUE TITLE
Adding License file / Hint in Readme

### ISSUE THREAD

**Issue by SusanthCom** [sethen/markdown-include#12]
A simple Suggestion,

After reading `package.json`, found the code is released under [ISC License](https://en.wikipedia.org/wiki/ISC_license). 

It would be nice if a separate licence file in repo and a hint at bottom of read file.

If acceptable, could make a PR 😄 

Good Work <3 

Thanks

**Comment by sethen** [comment]
Thanks for the kind words!

The license has been added to the documentation in SHA b9689332036e7d5ca8366171a0265236d9b76515 ... Thanks for the feedback!
